# Generated by Django 3.2.5 on 2021-09-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='resume',
            field=models.FileField(upload_to='static/media/resume'),
        ),
    ]
