# Generated by Django 3.2.5 on 2021-08-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='blogId',
            new_name='newsletterId',
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='img',
            field=models.ImageField(upload_to='static/images/newsletters'),
        ),
    ]
