# Generated by Django 3.2.5 on 2021-09-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_alter_contest_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='img',
            field=models.ImageField(upload_to='static/media/contests'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='result',
            field=models.FileField(blank=True, null=True, upload_to='static/media/result'),
        ),
    ]
