# Generated by Django 3.2.5 on 2021-08-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='commentsCnt',
            field=models.IntegerField(default=0, verbose_name='Comments Count'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='img',
            field=models.ImageField(upload_to='static/images/blog'),
        ),
    ]
