# Generated by Django 3.2.5 on 2021-09-12 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media/gallery')),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
